package acctelemetry

type AccPhysics struct {
	PacketID            int32
	Gas                 float32
	Brake               float32
	Fuel                float32
	Gear                int32
	RPMs                int32
	SteerAngle          float32
	SpeedKmh            float32
	Velocity            [3]float32
	AccG                [3]float32
	WheelSlip           [4]float32
	WheelLoad           [4]float32
	WheelsPressure      [4]float32
	WheelAngularSpeed   [4]float32
	TyreWear            [4]float32
	TyreDirtyLevel      [4]float32
	TyreCoreTemperature [4]float32
	CamberRAD           [4]float32
	SuspensionTravel    [4]float32
	DRS                 float32
	TC                  float32
	Heading             float32
	Pitch               float32
	Roll                float32
	CGHeight            float32
	CarDamage           [5]float32
	NumberOfTyresOut    int32
	PitLimiterOn        int32
	ABS                 float32
	KersCharge          float32
	KersInput           float32
	AutoShifterOn       int32
	RideHeight          [2]float32
	TurboBoost          float32
	Ballast             float32
	AirDensity          float32
	AirTemp             float32
	RoadTemp            float32
	LocalAngularVel     [3]float32
	FinalFF             float32
	PerformanceMeter    float32
	EngineBrake         int32
	ERSRecoveryLevel    int32
	ERSPowerLevel       int32
	ERSHeatCharging     int32
	ERSIsCharging       int32
	KersCurrentKJ       float32
	DRSAvailable        int32
	DRSEnabled          int32
	BrakeTemp           [4]float32
	Clutch              float32
	TyreTempI           [4]float32
	TyreTempM           [4]float32
	TyreTempO           [4]float32
	IsAIControlled      int32
	TyreContactPoint    [4][3]float32
	TyreContactNormal   [4][3]float32
	TyreContactHeading  [4][3]float32
	BrakeBias           float32
	LocalVelocity       [3]float32
	P2PActivations      int32
	P2PStatus           int32
	CurrentMaxRPM       int32
	MZ                  [4]float32
	FX                  [4]float32
	FY                  [4]float32
	SlipRatio           [4]float32
	SlipAngle           [4]float32
	TCInAction          int32
	ABSInAction         int32
	SuspensionDamage    [4]float32
	TyreTemp            [4]float32
}
