package types

type AccPhysics struct {
	PacketID            int32
	Gas                 float32
	Brake               float32
	Fuel                float32
	Gear                int32
	RPMs                int32
	SteerAngle          float64
	SpeedKmh            float64
	Velocity            [3]float64
	AccG                [3]float64
	WheelSlip           [4]float64
	WheelLoad           [4]float64
	WheelsPressure      [4]float64
	WheelAngularSpeed   [4]float64
	TyreWear            [4]float64
	TyreDirtyLevel      [4]float64
	TyreCoreTemperature [4]float64
	CamberRAD           [4]float64
	SuspensionTravel    [4]float64
	DRS                 float64
	TC                  float64
	Heading             float64
	Pitch               float64
	Roll                float64
	CGHeight            float64
	CarDamage           [5]float64
	NumberOfTyresOut    int32
	PitLimiterOn        int32
	ABS                 float64
	KersCharge          float64
	KersInput           float64
	AutoShifterOn       int32
	RideHeight          [2]float64
	TurboBoost          float64
	Ballast             float64
	AirDensity          float64
	AirTemp             float64
	RoadTemp            float64
	LocalAngularVel     [3]float64
	FinalFF             float64
	PerformanceMeter    float64
	EngineBrake         int32
	ERSRecoveryLevel    int32
	ERSPowerLevel       int32
	ERSHeatCharging     int32
	ERSIsCharging       int32
	KersCurrentKJ       float64
	DRSAvailable        int32
	DRSEnabled          int32
	BrakeTemp           [4]float64
	Clutch              float64
	TyreTempI           [4]float64
	TyreTempM           [4]float64
	TyreTempO           [4]float64
	IsAIControlled      int32
	TyreContactPoint    [4][3]float64
	TyreContactNormal   [4][3]float64
	TyreContactHeading  [4][3]float64
	BrakeBias           float64
	LocalVelocity       [3]float64
	P2PActivations      int32
	P2PStatus           int32
	CurrentMaxRPM       int32
	MZ                  [4]float64
	FX                  [4]float64
	FY                  [4]float64
	SlipRatio           [4]float64
	SlipAngle           [4]float64
	TCInAction          int32
	ABSInAction         int32
	SuspensionDamage    [4]float64
	TyreTemp            [4]float64
}
